apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app
    server: https://kubernetes.default.svc
  project: my-project
  source:
    path: argocd/my-apps/my-app3
    repoURL: https://github.com/mmanirmd/argocd-app.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
