apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-application
  namespace: argocd
spec:
  destination:
    namespace: team2
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/argo-apps
    repoURL: https://github.com/mmanirmd/argocd-app.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
